version: "3"
services:
  api:
    image: docker-node-mongo
    build: api/.
    ports:
      - "5000:5000"
    volumes:
      - ./api:/usr/src/app
    links:
      - db_postgres
    depends_on:
      - db_mongo
      - db_postgres
  db_mongo:
    image: mongo
    ports:
      - 27017:27017
  db_postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
      POSTGRES_USERNAME: docker
    volumes:
      - ./db/db_script.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    image: react-app
    ports:
      - 3000:3000
    stdin_open: true
    links:
      - api
    volumes:
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
