version: "3.8"
services:
  api:
    build:
      context: ./api
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - db_mongo
      - db_postgres
    networks:
      - internal
    ports:
      - "400:80"

  db_mongo:
    image: mongo
    restart: always
    networks:
      - internal
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouserksdfh
      MONGO_INITDB_ROOT_PASSWORD: lkdjfhg8dfubmd8fb

  db_postgres:
    build:
      context: ./db
      dockerfile: db.Dockerfile
    volumes:
      - ./var/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - internal
    environment:
      POSTGRES_PASSWORD: user_blog_password
      POSTGRES_DB: blog

  frontend:
    build:
      context: ./client
    restart: unless-stopped
    build: ./client
    ports:
      - "80:80"
    networks:
      - internal
    depends_on:
      - api

networks:
  internal:
    driver: bridge

volumes:
  blogpg:
