version: "3"
services:
  api:
    build:
      context: ./api
    volumes:
      - ./api:/usr/src/app
    links:
      - db_postgres
    depends_on:
      - db_mongo
      - db_postgres
    networks:
      - internal
    ports:
      - "400:80"
  db_mongo:
    image: mongo
    networks:
      - internal

  db_postgres:
    image: postgres
    restart: always
    networks:
      - internal
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
      POSTGRES_USERNAME: docker
    volumes:
      - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
      - "blogpg:/var/lib/postgresql/data"

  frontend:
    build:
      context: ./client
    restart: unless-stopped
    build: ./client
    ports:
      - "80:80"
    networks:
      - internal
    depends_on:
      - api

networks:
  internal:
    driver: bridge

volumes:
  blogpg:
