const userTypes = {
  USER_LOADING: "USER_LOADING",
  USER_LOADED: "USER_LOADED",
  AUTH_ERROR: "AUTH_ERROR",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",

  FETCH_USER: "FETCH_USER",
  FETCHED_USER_SUCCESS: "FETCHED_USER_SUCCESS",
};

export default userTypes;
