const userTypes = {
  USER_LOADING: 'USER_LOADING',
  USER_LOADED: 'USER_LOADED',
  AUTH_ERROR: 'AUTH_ERROR',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  FETCHED_USER_SUCCESS: 'FETCHED_USER_SUCCESS',
  FETCHED_USER_FAIL: 'FETCHED_USER_FAIL',
  FETCH_USER: 'FETCH_USER',
  REQUESTED_USER: 'REQUESTED_USER',
};

export default userTypes;
