const actionTypes = {
  SELECT_PATH: 'SELECT_PATH',
  LOAD_PATH: 'LOAD_PATH',
  LOADED_PATH: 'LOADED_PATH',
  SET_PATH: 'SET_PATH',
  LOAD_TITLE: 'LOAD_TITLE',
  SET_POST: 'SET_POST',
  ADD_HISTORY: 'ADD_HISTORY',
  SET_THEME_MODE: 'SET_THEME_MODE',
  MENU_SET_ACTIVE: 'MENU_SET_ACTIVE',
  LOAD_THEME: 'LOAD_THEME',
};

export default actionTypes;
