const actionTypes = {
  SELECT_PATH: "SELECT_PATH",
  LOAD_PATH: "LOAD_PATH",
  LOADED_PATH: "LOADED_PATH",
  SET_PATH: "SET_PATH",
  LOAD_TITLE: "LOAD_TITLE",
  SET_POST: "SET_POST",
  ADD_HISTORY: "ADD_HISTORY",
};

export default actionTypes;
