const blogTypes = {
  POSTS_LOADING: "POSTS_LOADING",
  POSTS_LOADED: "POSTS_LOADED",
  TOOLS_LOADED: "TOOLS_LOADED",
  TOOLS_LOADING: "TOOLS_LOADING",
  TOPIC_ADD: "TOPIC_ADD",
  TOPICS_LOADED: "TOPICS_LOADED",
  TOPICS_LOADING: "TOPICS_LOADING",
  TOPICS_TOOLS_LOADING: "TOPICS_TOOLS_LOADING",
  TOPICS_TOOLS_LOADED: "TOPICS_TOOLS_LOADED",
};

export default blogTypes;
